channels:
  - conda-forge
  - nvidia/label/cuda-11.3.0
dependencies:
  - python=3.9
  - pip=22.1.2 
  - cudatoolkit-dev=11.3
  - numpy=1.22.4
  - pillow=9.1.1
  - scipy=1.8.1
  - ffmpeg=5.0.1
  - tqdm=4.64.0  
  - pytorch::pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch::torchvision=0.13.1=py39_cu113
  - pytorch::torchaudio=0.12.1=py39_cu113
  - pip:
    - Cython==0.29.32
    - sacrebleu==1.5.1
    - sacremoses==0.0.53
    - omegaconf==2.0.6
