name: efficiency-benchmark-submission
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - nvidia::cudatoolkit=11.3
  - python=3.8
  - pytorch::pytorch
  - pip
  - pip:
    - numpy
    - transformers
    - datasets
    - sentencepiece
